-- AlterTable
ALTER TABLE "Outing" ADD COLUMN     "isApproved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "issuedBy" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "issuedTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Outpass" ADD COLUMN     "isApproved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "issuedBy" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "issuedTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
