-- AlterTable
ALTER TABLE "Outpass" ADD COLUMN     "rejectedBy" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "rejectedTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isRejected" SET DEFAULT false;
