-- AlterTable
ALTER TABLE "Outing" ALTER COLUMN "FromTime" SET DATA TYPE TIME,
ALTER COLUMN "ToTime" SET DATA TYPE TIME;

-- AlterTable
ALTER TABLE "Outpass" ALTER COLUMN "FromDay" SET DATA TYPE DATE,
ALTER COLUMN "ToDay" SET DATA TYPE DATE;
